# Generated by Django 4.1 on 2022-08-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appentregable', '0002_familia_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='nacimiento',
        ),
    ]
