# Generated by Django 4.1 on 2022-08-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentregable', '0007_remove_familia_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='nacimiento',
            field=models.DateField(default=True),
        ),
    ]
