# Generated by Django 4.1 on 2022-08-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appentregable', '0008_familia_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='nacimiento',
            field=models.DateField(),
        ),
    ]
